#!/bin/bash

# Script to generate test scripts from templates with actual credentials
# This keeps secrets out of git while making it easy to run tests

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_DIR="$SCRIPT_DIR/../iqq-infrastructure"

echo "=========================================="
echo "Generating Test Scripts with Credentials"
echo "=========================================="
echo ""

# Check if we're in the right directory
if [ ! -d "$INFRA_DIR" ]; then
    echo "❌ Error: iqq-infrastructure directory not found"
    echo "Please run this script from the repository root"
    exit 1
fi

# Change to infrastructure directory to run terraform commands
cd "$INFRA_DIR"

echo "Retrieving credentials from Terraform..."
echo ""

# Get Default Client credentials
DEFAULT_CLIENT_ID=$(terraform output -json cognito_partner_clients 2>/dev/null | jq -r '.default.client_id' || echo "")
DEFAULT_CLIENT_SECRET=$(terraform output -json cognito_partner_client_secrets 2>/dev/null | jq -r '.default' || echo "")
DEFAULT_API_KEY=$(terraform output -raw default_api_key_value 2>/dev/null || echo "")

# Get Partner A credentials
PARTNER_A_CLIENT_ID=$(terraform output -json cognito_partner_clients 2>/dev/null | jq -r '.partner_a.client_id' || echo "")
PARTNER_A_CLIENT_SECRET=$(terraform output -json cognito_partner_client_secrets 2>/dev/null | jq -r '.partner_a' || echo "")
PARTNER_A_API_KEY=$(terraform output -raw partner_a_api_key_value 2>/dev/null || echo "")

# Get Partner B credentials
PARTNER_B_CLIENT_ID=$(terraform output -json cognito_partner_clients 2>/dev/null | jq -r '.partner_b.client_id' || echo "")
PARTNER_B_CLIENT_SECRET=$(terraform output -json cognito_partner_client_secrets 2>/dev/null | jq -r '.partner_b' || echo "")
PARTNER_B_API_KEY=$(terraform output -raw partner_b_api_key_value 2>/dev/null || echo "")

if [ -z "$DEFAULT_CLIENT_ID" ]; then
    echo "❌ Error: Could not retrieve credentials from Terraform"
    echo "   Make sure Terraform has been applied in iqq-infrastructure/"
    exit 1
fi

echo "✓ Retrieved credentials from Terraform"
echo ""

# Generate test-client-id-mapping.sh
cat > "$SCRIPT_DIR/test-client-id-mapping.sh" << 'EOF'
#!/bin/bash

# Test script for API key to client ID mapping and validation
# Tests automatic client ID extraction and cross-validation
# Generated by generate-test-scripts.sh - DO NOT COMMIT

set -e

API_URL="https://r8ukhidr1m.execute-api.us-east-1.amazonaws.com/dev"
COGNITO_DOMAIN="https://iqq-dev-ib9i1hvt.auth.us-east-1.amazoncognito.com"

echo "=========================================="
echo "Testing API Key to Client ID Mapping"
echo "=========================================="
echo ""

echo "Test 1: Default Client (CLI001) with matching API key"
echo "Expected: Success, max 2 quotes, APCO blocked"
echo "------------------------------------------"

CLIENT_ID="DEFAULT_CLIENT_ID_PLACEHOLDER"
CLIENT_SECRET="DEFAULT_CLIENT_SECRET_PLACEHOLDER"
API_KEY="DEFAULT_API_KEY_PLACEHOLDER"

TOKEN=$(curl -s -X POST "${COGNITO_DOMAIN}/oauth2/token" \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -u "${CLIENT_ID}:${CLIENT_SECRET}" \
  -d "grant_type=client_credentials&scope=iqq-api/read" | jq -r '.access_token')

echo "OAuth Token obtained: ${TOKEN:0:20}..."

RESPONSE=$(curl -s -X GET "${API_URL}/package" \
  -H "Authorization: Bearer ${TOKEN}" \
  -H "x-api-key: ${API_KEY}")

echo "Response:"
echo "$RESPONSE" | jq '.'

QUOTE_COUNT=$(echo "$RESPONSE" | jq '.summary.totalQuotes // 0')
echo "Quotes returned: $QUOTE_COUNT"

if [ "$QUOTE_COUNT" -le 2 ]; then
  echo "✅ Test 1 PASSED: Max 2 quotes enforced"
else
  echo "❌ Test 1 FAILED: Expected max 2 quotes, got $QUOTE_COUNT"
fi

echo ""
echo "=========================================="
echo "Test Summary"
echo "=========================================="
echo "✅ Test 1: Default client with matching credentials"
EOF

# Replace placeholders
sed -i.bak "s/DEFAULT_CLIENT_ID_PLACEHOLDER/$DEFAULT_CLIENT_ID/g" "$SCRIPT_DIR/test-client-id-mapping.sh"
sed -i.bak "s/DEFAULT_CLIENT_SECRET_PLACEHOLDER/$DEFAULT_CLIENT_SECRET/g" "$SCRIPT_DIR/test-client-id-mapping.sh"
sed -i.bak "s/DEFAULT_API_KEY_PLACEHOLDER/$DEFAULT_API_KEY/g" "$SCRIPT_DIR/test-client-id-mapping.sh"
rm "$SCRIPT_DIR/test-client-id-mapping.sh.bak"

chmod +x "$SCRIPT_DIR/test-client-id-mapping.sh"
echo "✓ Generated: test-client-id-mapping.sh"

# Generate test-complete-client-mapping.sh
cat > "$SCRIPT_DIR/test-complete-client-mapping.sh" << 'EOF'
#!/bin/bash

# Comprehensive test script for API key to client ID mapping
# Tests all scenarios including validation and mismatch detection
# Generated by generate-test-scripts.sh - DO NOT COMMIT

set -e

API_URL="https://r8ukhidr1m.execute-api.us-east-1.amazonaws.com/dev"
COGNITO_DOMAIN="https://iqq-dev-ib9i1hvt.auth.us-east-1.amazoncognito.com"

echo "=========================================="
echo "Comprehensive Client ID Mapping Tests"
echo "=========================================="
echo ""

# Test 1: Default Client (CLI001)
echo "Test 1: Default Client (CLI001) with matching API key"
echo "Expected: Success, max 2 quotes, APCO blocked"
echo "------------------------------------------"

CLIENT_ID="DEFAULT_CLIENT_ID_PLACEHOLDER"
CLIENT_SECRET="DEFAULT_CLIENT_SECRET_PLACEHOLDER"
API_KEY="DEFAULT_API_KEY_PLACEHOLDER"

TOKEN=$(curl -s -X POST "${COGNITO_DOMAIN}/oauth2/token" \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -u "${CLIENT_ID}:${CLIENT_SECRET}" \
  -d "grant_type=client_credentials&scope=iqq-api/read" | jq -r '.access_token')

RESPONSE=$(curl -s -X GET "${API_URL}/package" \
  -H "Authorization: Bearer ${TOKEN}" \
  -H "x-api-key: ${API_KEY}")

QUOTE_COUNT=$(echo "$RESPONSE" | jq '.summary.totalQuotes // 0')
HAS_APCO=$(echo "$RESPONSE" | jq '[.providerQuotes[]? | select(.provider == "APCO Insurance")] | length')

echo "Quotes returned: $QUOTE_COUNT"
echo "APCO quotes: $HAS_APCO"

if [ "$QUOTE_COUNT" -le 2 ] && [ "$HAS_APCO" -eq 0 ]; then
  echo "✅ Test 1 PASSED: Max 2 quotes enforced, APCO blocked"
else
  echo "❌ Test 1 FAILED: Expected max 2 quotes with APCO blocked"
fi

echo ""
echo ""

# Test 2: Partner A Client (CLI002)
echo "Test 2: Partner A Client (CLI002) with matching API key"
echo "Expected: Success, only Client Direct and Route66"
echo "------------------------------------------"

CLIENT_ID="PARTNER_A_CLIENT_ID_PLACEHOLDER"
CLIENT_SECRET="PARTNER_A_CLIENT_SECRET_PLACEHOLDER"
API_KEY="PARTNER_A_API_KEY_PLACEHOLDER"

TOKEN=$(curl -s -X POST "${COGNITO_DOMAIN}/oauth2/token" \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -u "${CLIENT_ID}:${CLIENT_SECRET}" \
  -d "grant_type=client_credentials&scope=iqq-api/read" | jq -r '.access_token')

RESPONSE=$(curl -s -X GET "${API_URL}/package" \
  -H "Authorization: Bearer ${TOKEN}" \
  -H "x-api-key: ${API_KEY}")

QUOTE_COUNT=$(echo "$RESPONSE" | jq '.summary.totalQuotes // 0')
PROVIDERS=$(echo "$RESPONSE" | jq -r '[.providerQuotes[]?.provider] | join(", ")')

echo "Quotes returned: $QUOTE_COUNT"
echo "Providers: $PROVIDERS"

if [ "$QUOTE_COUNT" -eq 2 ]; then
  echo "✅ Test 2 PASSED: Only allowed providers returned"
else
  echo "❌ Test 2 FAILED: Expected 2 quotes from allowed providers"
fi

echo ""
echo ""

# Test 3: Client ID Mismatch
echo "Test 3: Client ID Mismatch (CLI001 token with CLI002 API key)"
echo "Expected: 403 Forbidden"
echo "------------------------------------------"

CLIENT_ID="DEFAULT_CLIENT_ID_PLACEHOLDER"
CLIENT_SECRET="DEFAULT_CLIENT_SECRET_PLACEHOLDER"
WRONG_API_KEY="PARTNER_A_API_KEY_PLACEHOLDER"

TOKEN=$(curl -s -X POST "${COGNITO_DOMAIN}/oauth2/token" \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -u "${CLIENT_ID}:${CLIENT_SECRET}" \
  -d "grant_type=client_credentials&scope=iqq-api/read" | jq -r '.access_token')

RESPONSE=$(curl -s -w "\nHTTP_CODE:%{http_code}" -X GET "${API_URL}/package" \
  -H "Authorization: Bearer ${TOKEN}" \
  -H "x-api-key: ${WRONG_API_KEY}")

HTTP_CODE=$(echo "$RESPONSE" | grep "HTTP_CODE:" | cut -d: -f2)
BODY=$(echo "$RESPONSE" | grep -v "HTTP_CODE:")

echo "HTTP Status: $HTTP_CODE"
echo "Response: $BODY"

if [ "$HTTP_CODE" -eq 403 ]; then
  echo "✅ Test 3 PASSED: Client ID mismatch correctly rejected"
else
  echo "❌ Test 3 FAILED: Expected 403 Forbidden, got $HTTP_CODE"
fi

echo ""
echo ""

# Test 4: Partner B Client (CLI003)
echo "Test 4: Partner B Client (CLI003) with no preferences"
echo "Expected: Success, all 3 providers"
echo "------------------------------------------"

CLIENT_ID="PARTNER_B_CLIENT_ID_PLACEHOLDER"
CLIENT_SECRET="PARTNER_B_CLIENT_SECRET_PLACEHOLDER"
API_KEY="PARTNER_B_API_KEY_PLACEHOLDER"

TOKEN=$(curl -s -X POST "${COGNITO_DOMAIN}/oauth2/token" \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -u "${CLIENT_ID}:${CLIENT_SECRET}" \
  -d "grant_type=client_credentials&scope=iqq-api/read" | jq -r '.access_token')

RESPONSE=$(curl -s -X GET "${API_URL}/package" \
  -H "Authorization: Bearer ${TOKEN}" \
  -H "x-api-key: ${API_KEY}")

QUOTE_COUNT=$(echo "$RESPONSE" | jq '.summary.totalQuotes // 0')
PROVIDERS=$(echo "$RESPONSE" | jq -r '[.providerQuotes[]?.provider] | join(", ")')

echo "Quotes returned: $QUOTE_COUNT"
echo "Providers: $PROVIDERS"

if [ "$QUOTE_COUNT" -eq 3 ]; then
  echo "✅ Test 4 PASSED: All providers returned (no preferences)"
else
  echo "❌ Test 4 FAILED: Expected 3 quotes, got $QUOTE_COUNT"
fi

echo ""
echo ""

echo "=========================================="
echo "Test Summary"
echo "=========================================="
echo "All tests completed. Check results above."
echo ""
echo "Key Features Verified:"
echo "✓ Automatic client ID extraction from API key tags"
echo "✓ OAuth token to business client ID mapping"
echo "✓ Cross-validation between API key and OAuth token"
echo "✓ Client preferences enforcement (blocklist, whitelist, max)"
echo "✓ 403 Forbidden on client ID mismatch"
EOF

# Replace placeholders
sed -i.bak "s/DEFAULT_CLIENT_ID_PLACEHOLDER/$DEFAULT_CLIENT_ID/g" "$SCRIPT_DIR/test-complete-client-mapping.sh"
sed -i.bak "s/DEFAULT_CLIENT_SECRET_PLACEHOLDER/$DEFAULT_CLIENT_SECRET/g" "$SCRIPT_DIR/test-complete-client-mapping.sh"
sed -i.bak "s/DEFAULT_API_KEY_PLACEHOLDER/$DEFAULT_API_KEY/g" "$SCRIPT_DIR/test-complete-client-mapping.sh"
sed -i.bak "s/PARTNER_A_CLIENT_ID_PLACEHOLDER/$PARTNER_A_CLIENT_ID/g" "$SCRIPT_DIR/test-complete-client-mapping.sh"
sed -i.bak "s/PARTNER_A_CLIENT_SECRET_PLACEHOLDER/$PARTNER_A_CLIENT_SECRET/g" "$SCRIPT_DIR/test-complete-client-mapping.sh"
sed -i.bak "s/PARTNER_A_API_KEY_PLACEHOLDER/$PARTNER_A_API_KEY/g" "$SCRIPT_DIR/test-complete-client-mapping.sh"
sed -i.bak "s/PARTNER_B_CLIENT_ID_PLACEHOLDER/$PARTNER_B_CLIENT_ID/g" "$SCRIPT_DIR/test-complete-client-mapping.sh"
sed -i.bak "s/PARTNER_B_CLIENT_SECRET_PLACEHOLDER/$PARTNER_B_CLIENT_SECRET/g" "$SCRIPT_DIR/test-complete-client-mapping.sh"
sed -i.bak "s/PARTNER_B_API_KEY_PLACEHOLDER/$PARTNER_B_API_KEY/g" "$SCRIPT_DIR/test-complete-client-mapping.sh"
rm "$SCRIPT_DIR/test-complete-client-mapping.sh.bak"

chmod +x "$SCRIPT_DIR/test-complete-client-mapping.sh"
echo "✓ Generated: test-complete-client-mapping.sh"

echo ""
echo "=========================================="
echo "Done!"
echo "=========================================="
echo ""
echo "Generated test scripts:"
echo "- scripts/test-client-id-mapping.sh"
echo "- scripts/test-complete-client-mapping.sh"
echo ""
echo "⚠️  IMPORTANT: These files contain secrets and are excluded from git"
echo ""
echo "To run tests:"
echo "  ./scripts/test-client-id-mapping.sh"
echo "  ./scripts/test-complete-client-mapping.sh"
echo ""
